function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 14-Jul-2023 12:39:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');
%imagesc(cdata1);
%colormap gray
caxis([0,5.25]); % comment this out when done

S = size(cdata1);
% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 S(1)+0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 S(2)+0.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'Layer','top');
% Create colorbar
colorbar('peer',axes1);

